config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users do
    resources :appointments, only: [:update, :show, :destroy, :index, :edit]
    get "d_1_t_1" => "appointments"
    get "d_1_t_2" => "appointments"
    get "d_1_t_3" => "appointments"
    get "d_1_t_4" => "appointments"
    get "d_1_t_5" => "appointments"
    get "d_1_t_6" => "appointments"

    get "d_2_t_1" => "appointments"
    get "d_2_t_2" => "appointments"
    get "d_2_t_3" => "appointments"
    get "d_2_t_4" => "appointments"
    get "d_2_t_5" => "appointments"
    get "d_2_t_6" => "appointments"

    get "d_3_t_1" => "appointments"
    get "d_3_t_2" => "appointments"
    get "d_3_t_3" => "appointments"
    get "d_3_t_4" => "appointments"
    get "d_3_t_5" => "appointments"
    get "d_3_t_6" => "appointments"

    get "d_4_t_1" => "appointments"
    get "d_4_t_2" => "appointments"
    get "d_4_t_3" => "appointments"
    get "d_4_t_4" => "appointments"
    get "d_4_t_5" => "appointments"
    get "d_4_t_6" => "appointments"

    get "d_5_t_1" => "appointments"
    get "d_5_t_2" => "appointments"
    get "d_5_t_3" => "appointments"
    get "d_5_t_4" => "appointments"
    get "d_5_t_5" => "appointments"
    get "d_5_t_6" => "appointments"

    get "d_6_t_1" => "appointments"
    get "d_6_t_2" => "appointments"
    get "d_6_t_3" => "appointments"
    get "d_6_t_4" => "appointments"
    get "d_6_t_5" => "appointments"
    get "d_6_t_6" => "appointments"

    get "d_7_t_1" => "appointments"
    get "d_7_t_2" => "appointments"
    get "d_7_t_3" => "appointments"
    get "d_7_t_4" => "appointments"
    get "d_7_t_5" => "appointments"
    get "d_7_t_6" => "appointments"
  end

  resources :users do
    resources :categories, only: [:create, :update, :destroy, :edit]
  end

  get 'categories' => 'categories#index', :as => :category_index

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'authorization_error' => 'users', :as => :authorization_error

  post "oauth2callback" => "oauths#callback"
  get "oauth2callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  # delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  get "create_weekly_hourly" => "availabilities", :as => :create_availability
  get "update_weekly_hourly" => "availabilities", :as => :update_availability

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, :dependent => :destroy
  has_many :trainee_appointments, class_name: :Appointment, foreign_key: :trainee_id
  has_many :trainer_appointments, class_name: :Appointment, foreign_key: :trainer_id
  has_many :availabilities
  has_one :category


  validates :name, :email, :address, presence: true
  validates :email, uniqueness: true

	  validates :password, length: { minimum: 8 }, on: :create
	  validates :password, confirmation: true, on: :create
	  validates :password_confirmation, presence: true, on: :create

  accepts_nested_attributes_for :authentications
  accepts_nested_attributes_for :category
  accepts_nested_attributes_for :trainee_appointments, allow_destroy: true
  accepts_nested_attributes_for :trainer_appointments, allow_destroy: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def has_linked_google?
     authentications.where(provider: 'google').present?
  end

  def self.search(search)
    where("name ILIKE ? OR address ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :destroy, :update]

  def new
    @user = User.new
  end

  def index
    @user = User.where(trainer: true)
    if params[:search]
      @user = User.search(params[:search]).order("name ASC")
    else
      @user = User.all.order("name ASC")
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if @user.trainer == true
        auto_login(@user)
        flash[:alert] = "Trainer Signed Up!"
        redirect_to user_url(@user)
      else
        auto_login(@user)
        flash[:alert] = "Trainee Signed Up!"
        redirect_to users_url
      end
    else
      flash[:alert] = "Failed to Signed Up!"
      render 'new'
    end
  end

  def show
    if session[:access_token] != nil
      render :show
    else
      redirect_to :authorization_error
    end
  end

  def edit

  end

  def update
    if @user.update_attributes(user_params) && @user.trainer == true && @user.category == nil
      @category = Category.create
      @user.category = @category
      flash[:alert] = "Pick Your Training Categories!"
      redirect_to "/users/#{@user.id}/categories/#{@category.id}/edit"
    else
      flash[:alert] = "Account Settings Updated!"
      redirect_to user_url
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

private

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :address, :bio, :latitude, :longitude, :trainer, :password, :password_confirmation,
    trainer_appointments_attributes: [:id, :summary, :event_start_time, :event_end_time, :event_invitation_status, :_destroy],
    trainee_appointments_attributes: [:id, :summary, :event_start_time, :event_end_time, :event_invitation_status, :_destroy])
  end

  def nearby_trainers
    @nearby_trainers = @user.where(trainer: true).nearbys(5, units: :km)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@user.errors.count, "error") %> Error occurred! Please try again!</h4>
    <ul class="error_msg">
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<div class="form_container">
  <div class="form">
  <%= f.label :name %></br>
  <%= f.text_field :name, placeholder: "Enter your name" %>
  </div><br>

  <div class="form">
    <%= f.label :email %></br>
    <%= f.text_field :email, placeholder: "Enter your email address" %>
  </div><br>

  <div class="form">
    <%= f.label :address %></br>
    <%= f.text_field :address, placeholder: "Enter your street address" %>
  </div>

  <div class="check_box">
    <p>Check here if you are a </p>
    <%= f.check_box :trainer %>
    <%= f.label :trainer %>
  </div>

  <div class="sub-cancel_button center-align">
    <button class="btn waves-effect waves-light orange" type="submit" name="action">Submit
    </button>
      <%= link_to "Cancel", user_url(@user), class:"waves-effect waves-light orange btn" %>
  </div>
</div>
<% end %>

app/views/users/_private_appointments_view.html.erb
<!DOCTYPE html>
<html>
  <body>
      <div class="container">
        <div class="row">
          <div class="col s12 l12">
            <div class="card grey lighten-3">
              <div class="card-content black-text center">
                <% if current_user.trainer_appointments == [] && current_user.trainee_appointments == [] %>
                  <h4>Currently no events!</h4></br>
                  <h6><%= link_to "Click here to book an appointment with our trainers!", category_index_path %></h6>
                <% else %>
                <h4> Your upcoming training events: </h4>
                <% current_user.trainer_appointments.each do |e| %>
                  <% if Time.at(e.event_end_time) < Time.now %>
                    <% e.destroy %>
                  <% else %>
                  <ul>
                    <%= e.summary %>:</br>
                    <%= Time.at(e.event_start_time).strftime("%A %d/%m/%Y %T") %> to</br>
                    <%= Time.at(e.event_end_time).strftime("%A %d/%m/%Y %T") %></br>
                    <%= link_to "Event Details", "/users/#{@user.id}/appointments/#{e.id}", class: "waves-effect waves-light orange lighten-1 btn"%>
                  </br>
                  <% end %>
                  </ul>
                <% end %>
                <% current_user.trainee_appointments.each do |e| %>
                  <% if Time.at(e.event_end_time) < Time.now %>
                    <% e.destroy %>
                  <% else %>
                  <ul>
                    <%= e.summary %>:</br>
                    <%= Time.at(e.event_start_time).strftime("%A %d/%m/%Y %T") %> to</br>
                    <%= Time.at(e.event_end_time).strftime("%A %d/%m/%Y %T") %></br>
                    <%= link_to "Event Details", "/users/#{@user.id}/appointments/#{e.id}", class: "waves-effect waves-light orange lighten-1 btn" %>
                  </br>
                  <% end %>
                  </ul>
                <% end %>
              <% if current_user.trainer_appointments == [] && current_user.trainee_appointments == [] %>
              <h6>Currently no events!</h6></br>
              <% end %>
      <% end %>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/_trainee_cards.html.erb
<!-- Materialize Card Layout -->
<!-- Card 1 Profile -->
<div class="container">
  <div class="row">
    <div class="col s6 pull-s3">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <%= image_tag "identity.png" %></br>
          <span class="card-title">Profile</span>
            <div class="user_profile">
              <div class="user_info">
                <p>User name: <div class="display"><%= @user.name %></div></p>
                <p>Email address: <div class="display"><%= @user.email %></div></p>
                <p>Street address: <div class="display"><%= @user.address %></div></p></br>
              </div>
            </div>
          <div class="card-action">
          <% if current_user == @user %>
            <p class="edit_link"><%= link_to "Edit your profile", "/users/#{@user.id}/edit" %></p></br>
          <% end %>
          <% if current_user == @user && current_user.trainer == true %>
            <p class="edit_link"><%= link_to "Choose your training categories!", "/users/#{@user.id}/categories/#{@user.category.id}/edit" %></p>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/_trainer_cards.html.erb
<!-- Materialize Card Layout -->
<!-- Card 1 Profile -->
<div class="container">
  <div class="row">
    <div class="col m6 s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <%= image_tag "identity.png" %></br>
          <span class="card-title">Profile</span>
            <div class="user_profile">
              <div class="user_info">
                <p>User name: <div class="display"><%= @user.name %></div></p>
                <p>Email address: <div class="display"><%= @user.email %></div></p>
                <p>Street address: <div class="display"><%= @user.address %></div></p></br>
              </div>
            </div>
          <div class="card-action">
          <% if current_user == @user %>
            <p class="edit_link"><%= link_to "Edit your profile", "/users/#{@user.id}/edit" %></p></br>
          <% end %>
          <% if current_user == @user && current_user.trainer == true %>
            <p class="edit_link"><%= link_to "Choose your training categories!", "/users/#{@user.id}/categories/#{@user.category.id}/edit" %></p>
          <% end %>
          <% if current_user != @user %>
            <%= @user.bio %>
          <% end %>
          </div>
        </div>
     </div>
   </div>
<!-- Card 2 Bio-->
<div class="col m6 s12">
  <div class="card orange darker-1">
    <div class="card-content white-text">
      <i class="medium mdi-action-description"></i></br>
      <span class="card-title">Training Categories</span>
        <% @user.category.attributes.each do |key, value| %>
          <% if value == true %>
            <div class="title"><%= "#{key.capitalize.split('_').join("")}" %></div>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div></br>

app/views/users/_trainer_profile_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@user.errors.count, "error") %> Error occurred! Please try again!</h4>
    <ul class="error_msg">
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<div class="form_container">
  <div class="form">
  <%= f.label :name %></br>
  <%= f.text_field :name, placeholder: "Enter your name" %>
  </div><br>

  <div class="form">
    <%= f.label :email %></br>
    <%= f.text_field :email, placeholder: "Enter your email address" %>
  </div><br>

  <div class="form">
    <%= f.label :address %></br>
    <%= f.text_field :address, placeholder: "Enter your street address" %>
  </div>

  <div class="trainer_bio">
    <%= f.label :bio, "Tell us who you are, 200 words or less:" %>
    <%= f.text_area :bio %></br>
  </div>

  <div class="check_box">
    <p>Check here if you are a </p>
    <%= f.check_box :trainer %>
    <%= f.label :trainer %>
  </div>

  <div class="sub-cancel_button center-align">
    <button class="btn waves-effect waves-light orange" type="submit" name="action">Submit
    </button>
      <%= link_to "Cancel", user_url(@user), class:"waves-effect waves-light orange btn" %>
  </div>
</div>
<% end %>

app/views/users/authorization_error.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="container">
      <div class="row">
        <div class="col l8 offset-l4"></br>
          <%= link_to "PLEASE CLICK HERE TO LOGIN WITH GOOGLE!", auth_at_provider_path(:provider => :google), class:"waves-effect waves-light orange lighten-1 btn" %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<% if current_user == @user && current_user.trainer == true %>
  <h3>Update Your Profile</h3>
  <%= render 'trainer_profile_form' %>
<% elsif current_user == @user && current_user.trainer == false %>
  <h3>Update Your Profile</h3>
  <%= render 'form' %>
<% else %>
  <h3>Please login to edit this page!</h3>
<% end %>

app/views/users/index.html.erb
<div class="parallax-container">
  <div class="parallax"><%= image_tag("O7MF4F0.jpg")%></div>
    <div class="container">
      <div class="row">
        <div class="col l10 offset-l1 white-text">
          <h1>Find a trainer in your area</h1>
            <div class="search_bar">
              <%= form_tag(users_url, :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], placeholder: "BY NAME OR ADDRESS", required: true %>
                <%= submit_tag "Search", class:"waves-effect waves-light orange lighten-1 btn" %></br>
                <% end %>
               </div>
               <div class="search_category">
              <h4>Or... <%= link_to "search by training category", "/categories" %></h4>
            </div></br>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

<h3>Trainer Index:</h3>
  <div class="trainer_count">
    <p><%= @user.where(:trainer => true).count %> Trainers found!</p>
  </div>

<% @user.each do |t|%>
  <% if t.trainer == true %>
  <div class="row">
    <div class="col s10 m4 offset-l4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <div class="trainer_list">
              <h4><%=link_to "#{t.name}", "/users/#{t.id}" %></h4>
                <% if t.category != nil %>
                  <% t.category.attributes.each do |key, value| %>
                    <% if value == true %>
                    <h6><%= "#{key.capitalize}" %></h6>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if current_user == @user %>
  <h3 class="user_welcome">Welcome <%= @user.name %>!</h3>
<% else %>
  <h3 class="user_header"><%= @user.name %>'s page</h3>
<% end %></br>

<!-- TRAINER CARDS VS. TRAINEE CARDS -->
<% if @user.trainer == true %>
 <%= render 'trainer_cards' %>
<% else %>
 <%= render 'trainee_cards'%>
<% end %>

<div class="divider"></div>
<!-- PUBLIC PROFILE -->
<% if current_user != @user %>
  <%= render 'public_availability_view' %>
<% else %>
<!-- PRIVATE PROFILE -->
  <%= render 'private_appointments_view' %>
<% end %>


<div class="divider"></div></br>

<div style="text-align: center;">
<% if logged_in? %>
  Currently logged in as: <%= current_user.email %> | Account linked with Google!
<% end %>
</div>