config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users do
    resources :appointments, only: [:update, :show, :destroy, :index, :edit]
    get "d_1_t_1" => "appointments"
    get "d_1_t_2" => "appointments"
    get "d_1_t_3" => "appointments"
    get "d_1_t_4" => "appointments"
    get "d_1_t_5" => "appointments"
    get "d_1_t_6" => "appointments"

    get "d_2_t_1" => "appointments"
    get "d_2_t_2" => "appointments"
    get "d_2_t_3" => "appointments"
    get "d_2_t_4" => "appointments"
    get "d_2_t_5" => "appointments"
    get "d_2_t_6" => "appointments"

    get "d_3_t_1" => "appointments"
    get "d_3_t_2" => "appointments"
    get "d_3_t_3" => "appointments"
    get "d_3_t_4" => "appointments"
    get "d_3_t_5" => "appointments"
    get "d_3_t_6" => "appointments"

    get "d_4_t_1" => "appointments"
    get "d_4_t_2" => "appointments"
    get "d_4_t_3" => "appointments"
    get "d_4_t_4" => "appointments"
    get "d_4_t_5" => "appointments"
    get "d_4_t_6" => "appointments"

    get "d_5_t_1" => "appointments"
    get "d_5_t_2" => "appointments"
    get "d_5_t_3" => "appointments"
    get "d_5_t_4" => "appointments"
    get "d_5_t_5" => "appointments"
    get "d_5_t_6" => "appointments"

    get "d_6_t_1" => "appointments"
    get "d_6_t_2" => "appointments"
    get "d_6_t_3" => "appointments"
    get "d_6_t_4" => "appointments"
    get "d_6_t_5" => "appointments"
    get "d_6_t_6" => "appointments"

    get "d_7_t_1" => "appointments"
    get "d_7_t_2" => "appointments"
    get "d_7_t_3" => "appointments"
    get "d_7_t_4" => "appointments"
    get "d_7_t_5" => "appointments"
    get "d_7_t_6" => "appointments"
  end

  resources :users do
    resources :categories, only: [:create, :update, :destroy, :edit]
  end

  get 'categories' => 'categories#index', :as => :category_index

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'authorization_error' => 'users', :as => :authorization_error

  post "oauth2callback" => "oauths#callback"
  get "oauth2callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  # delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  get "create_weekly_hourly" => "availabilities", :as => :create_availability
  get "update_weekly_hourly" => "availabilities", :as => :update_availability

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :trainer, class_name: :User
  belongs_to :trainee, class_name: :User

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :require_login
  before_action :load_user
  before_action :load_appointment, only: [:show, :destroy]

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.create(appointment_params)
  end

  def create_event
    @appointment = Appointment.create(
       summary: "#{current_user.name}'s Training Session with #{@user.name}",
       address: "#{@user.address}",
       event_start_time: "#{@up}",
       event_end_time: "#{@low}",
       event_invitation_status: true,
       trainee_id: "#{current_user.id}",
       trainer_id: "#{@user.id}",
       google_event_id: "#{@result.id}"
     )
  end

  def show

  end

  def index

  end

  def destroy
    @appointment.destroy
    delete_google
    flash[:alert] = "Appointment Deleted!"
    redirect_to "/users/#{@user.id}"
  end

  def d_1_t_1
    @day = Date.today + 1
    @t_1 = Time.parse("14:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("15:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_1_t_2
    @day = Date.today + 1
    @t_1 = Time.parse("15:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("17:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_1_t_3
    @day = Date.today + 1
    @t_1 = Time.parse("17:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("18:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_1_t_4
    @day = Date.today + 1
    @t_1 = Time.parse("18:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("20:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_1_t_5
    @day = Date.today + 1
    @t_1 = Time.parse("20:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("21:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_1_t_6
    @day = Date.today + 1
    @t_1 = Time.parse("21:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("23:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_2_t_1
    @day = Date.today + 2
    @t_1 = Time.parse("14:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("15:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_2_t_2
    @day = Date.today + 2
    @t_1 = Time.parse("15:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("17:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_2_t_3
    @day = Date.today + 2
    @t_1 = Time.parse("17:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("18:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_2_t_4
    @day = Date.today + 2
    @t_1 = Time.parse("18:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("20:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_2_t_5
    @day = Date.today + 2
    @t_1 = Time.parse("20:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("21:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_2_t_6
    @day = Date.today + 2
    @t_1 = Time.parse("21:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("23:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_3_t_1
    @day = Date.today + 3
    @t_1 = Time.parse("14:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("15:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_3_t_2
    @day = Date.today + 3
    @t_1 = Time.parse("15:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("17:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_3_t_3
    @day = Date.today + 3
    @t_1 = Time.parse("17:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("18:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_3_t_4
    @day = Date.today + 3
    @t_1 = Time.parse("18:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("20:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_3_t_5
    @day = Date.today + 3
    @t_1 = Time.parse("20:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("21:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_3_t_6
    @day = Date.today + 3
    @t_1 = Time.parse("21:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("23:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_4_t_1
    @day = Date.today + 4
    @t_1 = Time.parse("14:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("15:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_4_t_2
    @day = Date.today + 4
    @t_1 = Time.parse("15:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("17:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_4_t_3
    @day = Date.today + 4
    @t_1 = Time.parse("17:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("18:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_4_t_4
    @day = Date.today + 4
    @t_1 = Time.parse("18:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("20:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_4_t_5
    @day = Date.today + 4
    @t_1 = Time.parse("20:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("21:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_4_t_6
    @day = Date.today + 4
    @t_1 = Time.parse("21:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("23:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_5_t_1
    @day = Date.today + 5
    @t_1 = Time.parse("15:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("17:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_5_t_2
    @day = Date.today + 5
    @t_1 = Time.parse("15:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("17:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_5_t_3
    @day = Date.today + 5
    @t_1 = Time.parse("17:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("18:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_5_t_4
    @day = Date.today + 5
    @t_1 = Time.parse("18:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("20:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_5_t_5
    @day = Date.today + 5
    @t_1 = Time.parse("20:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("21:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_5_t_6
    @day = Date.today + 5
    @t_1 = Time.parse("21:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("23:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_6_t_1
    @day = Date.today + 6
    @t_1 = Time.parse("14:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("15:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_6_t_2
    @day = Date.today + 6
    @t_1 = Time.parse("15:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("17:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_6_t_3
    @day = Date.today + 6
    @t_1 = Time.parse("17:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("18:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_6_t_4
    @day = Date.today + 6
    @t_1 = Time.parse("18:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("20:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_6_t_5
    @day = Date.today + 6
    @t_1 = Time.parse("20:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("21:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_6_t_6
    @day = Date.today + 6
    @t_1 = Time.parse("21:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("23:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_7_t_1
    @day = Date.today + 7
    @t_1 = Time.parse("14:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("15:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_7_t_2
    @day = Date.today + 7
    @t_1 = Time.parse("15:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("17:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_7_t_3
    @day = Date.today + 7
    @t_1 = Time.parse("17:00").seconds_since_midnight.seconds
    @t_2 = Time.parse("18:30").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_7_t_4
    @day = Date.today + 7
    @t_1 = Time.parse("18:30").seconds_since_midnight.seconds
    @t_2 = Time.parse("20:00").seconds_since_midnight.seconds
    insert_google_event
    @appointment = create_event
  end

  def d_7_t_5

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/views/appointments/d_1_t_4.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_2_t_1.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_2_t_2.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_2_t_4.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_3_t_1.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_3_t_2.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_3_t_4.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_4_t_5.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_5_t_2.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_6_t_6.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_7_t_3.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/d_7_t_5.html.erb
<!DOCTYPE html>
<html>
  <body>
    </br>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card grey lighten-4">
            <div class="card-content black-text center">
              <span class="card-title">You are booked!</span>
              <p>Please review your requested time slot below.</br>The appointment will appear on your Google Calendar momentarily.</p>
              </br>
              <% @appointment %>
              <%= flash[:notice] = "Invitation sent for #{@up.strftime("%A %d/%m/%Y %T")} to #{@low.strftime("%A %d/%m/%Y %T")}" %>
              <div class="section">
                <%= link_to "update your availability", :update_availability, class: "waves-effect waves-light orange lighten-1 btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/appointments/news.html.erb
<h3>Appointment#news</h3>
<p>
<%= appointment.new %>
</p>

app/views/appointments/show.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="container">
      <div class="row">
        <div class="col s10 pull-s1">
          <div class="card blue-grey lighten-4">
            <div class="card-content black-text">
              <%= image_tag "identity.png" %></br>
              <span class="card-title">Training session details</span>
                <div class="user_profile">
                  <div class="user_info">
                    <h5><%= @appointment.summary %></h5>
                    <p>Start Time: <div class="display_event"><%= @appointment.event_start_time  %></div></p>
                    <p>End Time: <div class="display_event"><%= @appointment.event_end_time %></div></p></br>
                    <p>Trainer Location: <div class="display_event"><%= @appointment.address %></div></p></br>
                  </div>
                </div>

          <div class="sub-cancel_button center-align">
            <button class="btn waves-effect waves-light orange" type="submit" name="action">
              <%= button_to "delete", {:controller => :appointments, :action => 'destroy', :id => @appointment.id }, :method => :delete %>
            </button>
              <%= link_to "Back to your profile", user_url(@user), class:"btn waves-effect waves-light orange" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  </body>
</html>