config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users do
    resources :appointments, only: [:update, :show, :destroy, :index, :edit]
    get "d_1_t_1" => "appointments"
    get "d_1_t_2" => "appointments"
    get "d_1_t_3" => "appointments"
    get "d_1_t_4" => "appointments"
    get "d_1_t_5" => "appointments"
    get "d_1_t_6" => "appointments"

    get "d_2_t_1" => "appointments"
    get "d_2_t_2" => "appointments"
    get "d_2_t_3" => "appointments"
    get "d_2_t_4" => "appointments"
    get "d_2_t_5" => "appointments"
    get "d_2_t_6" => "appointments"

    get "d_3_t_1" => "appointments"
    get "d_3_t_2" => "appointments"
    get "d_3_t_3" => "appointments"
    get "d_3_t_4" => "appointments"
    get "d_3_t_5" => "appointments"
    get "d_3_t_6" => "appointments"

    get "d_4_t_1" => "appointments"
    get "d_4_t_2" => "appointments"
    get "d_4_t_3" => "appointments"
    get "d_4_t_4" => "appointments"
    get "d_4_t_5" => "appointments"
    get "d_4_t_6" => "appointments"

    get "d_5_t_1" => "appointments"
    get "d_5_t_2" => "appointments"
    get "d_5_t_3" => "appointments"
    get "d_5_t_4" => "appointments"
    get "d_5_t_5" => "appointments"
    get "d_5_t_6" => "appointments"

    get "d_6_t_1" => "appointments"
    get "d_6_t_2" => "appointments"
    get "d_6_t_3" => "appointments"
    get "d_6_t_4" => "appointments"
    get "d_6_t_5" => "appointments"
    get "d_6_t_6" => "appointments"

    get "d_7_t_1" => "appointments"
    get "d_7_t_2" => "appointments"
    get "d_7_t_3" => "appointments"
    get "d_7_t_4" => "appointments"
    get "d_7_t_5" => "appointments"
    get "d_7_t_6" => "appointments"
  end

  resources :users do
    resources :categories, only: [:create, :update, :destroy, :edit]
  end

  get 'categories' => 'categories#index', :as => :category_index

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'authorization_error' => 'users', :as => :authorization_error

  post "oauth2callback" => "oauths#callback"
  get "oauth2callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  # delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  get "create_weekly_hourly" => "availabilities", :as => :create_availability
  get "update_weekly_hourly" => "availabilities", :as => :update_availability

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= favicon_link_tag 'favicon.ico'%>
  <head>
    <title>Phyziq</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- <script src="jquery.raty.js"></script> -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= csrf_meta_tags %>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <!-- <link type="text/css" rel="stylesheet" href="/css/materialize.min.css"  media="screen,projection"/> -->
  </head>
  <body>
  <header class="site-header">
    <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
      <% if current_user %>
      <li class="divider"></li>
      <li><%= link_to "Profile", "/users/#{session[:user_id]}" %></li>
      <li class="divider"></li>
      <li><%= link_to "Settings", "/users/#{session[:user_id]}/edit" %></li>
      <li class="divider"></li>
      <% if current_user.trainer == true %>
        <li><%= link_to "Training Categories", "/users/#{session[:user_id]}/categories/#{current_user.category.id}/edit" %></li>
        <li class="divider"></li>
      <% end %>
      <li><%= link_to "Update Availability", :update_availability %></li>
        <li class="divider"></li>
        <li><%= link_to 'Logout', :logout %></li>
      <% end %>
    </ul>
    <!-- navigation bar -->
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo center"><%= image_tag "phyziq-logo.png", :class => "logo" %></a>
        <% if !current_user %>
          <%= link_to "Login with Google", auth_at_provider_path(:provider => :google) %>
        <% else %>
          <%= link_to "Home", users_url %>
        <% end %>
        <ul id="nav-mobile" class="left show-on-med-and-down">
          <% if flash[:alert] %>
            <li><div id="google-alert" class="alert"><%= flash[:alert] %></div></li>
          <% end %>
          <% if current_user %>
          <!-- Dropdown Trigger -->
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="medium mdi-action-reorder"></i></a></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>
    <%= yield %>
  <!--Import jQuery before materialize.js-->
      <!-- <script type="text/javascript" src="js/materialize.min.js"></script> -->
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l7 s12 offset-1">
          <h5 class="black-text text-darken-2">About us:</h5>
          <p class="black-text text-darken-2">Currently, there are limited resources when people are looking for personal fitness training.  Phyziq.com is a website that connects personal fitness trainers and their customers. We provide booking tools that eases the headache of scheduling through phone and text between the two parties. Trainers are also able to promote themselves in their local area through their user profile and our trainer recommendation tools.</p>
        </div>
        <div class="col l3 s12 offset-1">
          <h5 class="black-text text-darken-2">Follow us on:</h5>
            <ul>
              <li><a class="black-text text-darken-2" href="#!">Facebook</a></li>
              <li><a class="black-text text-darken-2" href="#!">Twitter</a></li>
              <li><a class="black-text text-darken-2" href="#!">Instagram</a></li>
              <li><a class="black-text text-darken-2" href="#!">Contact</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright black-text">
        <div class="container center">
        © 2016 All rights reserved by Phyziq Fitness
        <!-- <a class="grey-text text-lighten-4 right" href="#!"></a> -->
        </div>
      </div>
    </footer>
  </body>
</html>